name: Latest blog post workflow
on:
  repository_dispatch:
    types: [contentful.deploy]
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/wait-action@master
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://preview.contentful.com/spaces/iw94f7ho69tg/environments/master/content_types/blockCards?access_token=sthThfu2AHyzzpZTCLQATQOVmG_iiX4YBy_c6BF_jz8"
          commit_message: "Updated README with latest blog posts"
